version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    open-pull-requests-limit: 3
    schedule:
      interval: monthly
    labels:
      - "type/dependencies"
    commit-message:
      prefix: ci
      include: scope

  - package-ecosystem: npm
    directory: '/'
    open-pull-requests-limit: 3
    schedule:
      interval: weekly
    labels:
      - "type/dependencies"
    commit-message:
      prefix: ci
      include: scope
    ignore:
      - dependency-name: escape-string-regexp
      - dependency-name: string-width
      - dependency-name: "@handsontable/react"
      - dependency-name: handsontable
      - dependency-name: reveal.js

