version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
    ignore:
      - dependency-name: escape-string-regexp
      - dependency-name: string-width
      - dependency-name: "@handsontable/react"
      - dependency-name: handsontable

