queue_rules:
  - name: default
    allow_inplace_checks: false
    queue_conditions:
      - '#approved-reviews-by >= 2'
      - check-success = "check-title"
      - check-success = "Node CI for slackbot-proxy"
      - check-success = "Node CI for app development"
    merge_conditions:
      - '#approved-reviews-by >= 2'
      - check-success = "check-title"
      - check-success = "Node CI for slackbot-proxy"
      - check-success = "Node CI for app development"
      - check-success = "Node CI for app production"

pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author = dependabot[bot]
      - '#approved-reviews-by >= 1'
      - check-success = "check-title"
      - check-success ~= Node CI for slackbot-proxy / .*
      - check-success ~= Node CI for app development / .*
      - check-success = test-prod-node20
      - check-success ~= test-prod-node20
      - check-success ~= test-prod-node20 / .*
    actions:
      merge:
        method: merge

  - name: Automatic merge for Preparing next version
    conditions:
      - author = github-actions[bot]
      - label = "type/prepare-next-version"
    actions:
      merge:
        method: merge
