queue_rules:
  - name: default
    allow_inplace_checks: false
    queue_conditions:
      - '#check-failure = 0'
      - or:
        - and:
            - check-success ~= ci-slackbot-proxy-
        - and:
            - check-success ~= ci-app-
    merge_conditions:
      - '#check-failure = 0'
      - or:
        - and:
            - check-success ~= ci-slackbot-proxy-
        - and:
            - check-success ~= ci-app-
            - check-success ~= test-prod-node20 /

pull_request_rules:
  - name: Automatic queue to merge
    conditions:
      - '#approved-reviews-by >= 1'
      - '#review-requested = 0'
      - check-success = "check-title"
    actions:
      queue:

  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author = dependabot[bot]
      - '#approved-reviews-by >= 1'
      - '#check-failure = 0'
      - check-success = "check-title"
    actions:
      merge:
        method: merge

  - name: Automatic merge for Preparing next version
    conditions:
      - author = github-actions[bot]
      - label = "type/prepare-next-version"
    actions:
      merge:
        method: merge
