pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author = dependabot[bot]
      - '#approved-reviews-by >= 1'
      - check-success = "lint (16.x)"
      - check-success = "test (16.x)"
      - check-success = "launch-dev (16.x)"
      - check-success = "test-prod-node14 / launch-prod"
      - check-success = "test-prod-node16 / launch-prod"
    actions:
      merge:
        method: merge
  - name: Automatic update for PR
    conditions:
      - author = dependabot[bot]
    actions:
      update:
