services:
  node:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ..:/workspace/growi:delegated
      - pnpm-store:/workspace/growi/.pnpm-store
      - node_modules:/workspace/growi/node_modules
      - node_modules_app:/workspace/growi/apps/app/node_modules
      - node_modules_slackbot-proxy:/workspace/growi/apps/slackbot-proxy/node_modules
      - buildcache_app:/workspace/growi/apps/app/.next
      - ../../growi-docker-compose:/workspace/growi-docker-compose:delegated
    tty: true

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - 27017
    volumes:
      - /data/db

  # This container requires '../../growi-docker-compose' repository
  #   cloned from https://github.com/weseek/growi-docker-compose.git
  elasticsearch:
    build:
      context: ../../growi-docker-compose/elasticsearch/v8
      dockerfile: ./Dockerfile
      args:
        - version=8.7.0
    restart: unless-stopped
    ports:
      - 9200
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true # CVE-2021-44228 mitigation for Elasticsearch <= 6.8.20/7.16.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/elasticsearch/data
      - ../../growi-docker-compose/elasticsearch/v8/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

volumes:
  pnpm-store:
  node_modules:
  node_modules_app:
  node_modules_slackbot-proxy:
  buildcache_app:
