#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

services:
  app:
    # Uncomment the next line to use a non-root user for all processes. You can also
    # simply use the "remoteUser" property in devcontainer.json if you just want VS Code
    # and its sub-processes (terminals, tasks, debugging) to execute as the user. On Linux,
    # you may need to update USER_UID and USER_GID in .devcontainer/Dockerfile to match your
    # user if not 1000. See https://aka.ms/vscode-remote/containers/non-root for details.
    user: node

    build:
      context: .
      dockerfile: ./app/Dockerfile

    volumes:
      - ..:/workspace/growi:delegated
      - node_modules:/workspace/growi/node_modules
      - node_modules_app:/workspace/growi/apps/app/node_modules
      - node_modules_slackbot-proxy:/workspace/growi/apps/slackbot-proxy/node_modules
      - buildcache_app:/workspace/growi/apps/app/.next
      - ../../growi-docker-compose:/workspace/growi-docker-compose:delegated
      - page_bulk_export_tmp:/tmp/page-bulk-export

    tty: true

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - 27017
    volumes:
      - /data/db

  # This container requires '../../growi-docker-compose' repository
  #   cloned from https://github.com/weseek/growi-docker-compose.git
  elasticsearch:
    build:
      context: ../../growi-docker-compose/elasticsearch/v8
      dockerfile: ./Dockerfile
      args:
        - version=8.7.0
    restart: unless-stopped
    ports:
      - 9200
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true # CVE-2021-44228 mitigation for Elasticsearch <= 6.8.20/7.16.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/elasticsearch/data
      - ../../growi-docker-compose/elasticsearch/v8/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  pdf-converter:
    user: node
    build:
      context: .
      dockerfile: ./pdf-converter/Dockerfile
    restart: unless-stopped
    ports:
      - 3010
    volumes:
      - ..:/workspace/growi:delegated
      - node_modules:/workspace/growi/node_modules
      - node_modules_pdf_converter:/workspace/growi/apps/pdf-converter/node_modules
      - page_bulk_export_tmp:/tmp/page-bulk-export
    tty: true

volumes:
  node_modules:
  node_modules_app:
  node_modules_slackbot-proxy:
  node_modules_pdf_converter:
  buildcache_app:
  page_bulk_export_tmp:
