version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: 1
    IMAGE_TAG: ''
  secrets-manager:
    DOCKER_REGISTRY_PASSWORD: growi/official-image-builder:DOCKER_REGISTRY_PASSWORD

phases:
  pre_build:
    commands:
      # install Git LFS
      - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash
      - yum install -y git-lfs
      # fetch LFS files
      - git-lfs pull
      # login to docker.io
      - echo ${DOCKER_REGISTRY_PASSWORD} | docker login --username wsmoogle --password-stdin
  build:
    commands:
      - docker build -t ${IMAGE_TAG} -f ./apps/app/docker/Dockerfile .

  post_build:
    commands:
      - docker push $IMAGE_TAG

cache:
  paths:
    - .pnpm-store/**/*
