name: Node CI for app development

on:
  push:
    branches-ignore:
      - release/**
      - rc/**
    paths:
      - .github/workflows/ci-app.yml
      - .eslint*
      - tsconfig.base.json
      - turbo.json
      - yarn.lock
      - package.json
      - apps/app/**
      - '!apps/app/docker/**'
      - packages/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  ci-app-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Cache/Restore node_modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            !**/node_modules/.cache/turbo
          key: node_modules-app-devdependencies-${{ runner.OS }}-node${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node_modules-app-devdependencies-${{ runner.OS }}-node${{ matrix.node-version }}-

      - name: Cache/Restore dist
        uses: actions/cache@v4
        with:
          path: |
            **/.turbo
            **/dist
            **/node_modules/.cache/turbo
          key: dist-ci-app-${{ runner.OS }}-node${{ matrix.node-version }}-${{ github.sha }}
          restore-keys: |
            dist-ci-app-${{ runner.OS }}-node${{ matrix.node-version }}-

      - name: Install dependencies
        run: |
          yarn global add turbo
          yarn global add node-gyp
          yarn --frozen-lockfile

      - name: Lint
        run: |
          turbo run lint --filter=!@growi/slackbot-proxy

      - name: Slack Notification
        uses: weseek/ghaction-slack-notification@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: '*Node CI for growi - lint (${{ matrix.node-version }})*'
          channel: '#ci'
          isCompactMode: true
          url: ${{ secrets.SLACK_WEBHOOK_URL }}


  ci-app-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017/tcp

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Cache/Restore node_modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            !**/node_modules/.cache/turbo
          key: node_modules-app-devdependencies-${{ runner.OS }}-node${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node_modules-app-devdependencies-${{ runner.OS }}-node${{ matrix.node-version }}-

      - name: Cache/Restore dist
        uses: actions/cache@v4
        with:
          path: |
            **/.turbo
            **/dist
            **/node_modules/.cache/turbo
          key: dist-ci-app-${{ runner.OS }}-node${{ matrix.node-version }}-${{ github.sha }}
          restore-keys: |
            dist-ci-app-${{ runner.OS }}-node${{ matrix.node-version }}-

      - name: Install dependencies
        run: |
          yarn global add turbo
          yarn global add node-gyp
          yarn --frozen-lockfile

      - name: Test
        run: |
          turbo run test --filter=!@growi/slackbot-proxy --env-mode=loose
        env:
          MONGO_URI: mongodb://localhost:${{ job.services.mongodb.ports['27017'] }}/growi_test

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Coverage Report
          path: |
            apps/app/coverage
            packages/remark-growi-directive/coverage

      - name: Slack Notification
        uses: weseek/ghaction-slack-notification@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: '*Node CI for growi - test (${{ matrix.node-version }})*'
          channel: '#ci'
          isCompactMode: true
          url: ${{ secrets.SLACK_WEBHOOK_URL }}


  ci-app-launch-dev:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017/tcp

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Cache/Restore node_modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            !**/node_modules/.cache/turbo
          key: node_modules-app-devdependencies-${{ runner.OS }}-node${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node_modules-app-devdependencies-${{ runner.OS }}-node${{ matrix.node-version }}-
            node_modules-app-devdependencies-${{ runner.OS }}-node${{ matrix.node-version }}-

      - name: Cache/Restore dist
        uses: actions/cache@v4
        with:
          path: |
            **/.turbo
            **/dist
            **/node_modules/.cache/turbo
          key: dist-ci-app-${{ runner.OS }}-node${{ matrix.node-version }}-${{ github.sha }}
          restore-keys: |
            dist-ci-app-${{ runner.OS }}-node${{ matrix.node-version }}-

      - name: Install dependencies
        run: |
          yarn global add turbo
          yarn global add node-gyp
          yarn --frozen-lockfile

      - name: turbo run dev:ci
        working-directory: ./apps/app
        run: |
          cp config/ci/.env.local.for-ci .env.development.local
          turbo run dev:ci --env-mode=loose
        env:
          MONGO_URI: mongodb://localhost:${{ job.services.mongodb.ports['27017'] }}/growi_dev

      - name: Slack Notification
        uses: weseek/ghaction-slack-notification@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: '*Node CI for growi - launch-dev (${{ matrix.node-version }})*'
          channel: '#ci'
          isCompactMode: true
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
