name: Create RC release Branche with the Scheduler (for dev/7.0.x)

# on:
#   schedule:
#     - cron: '0 0 * * *'

on:
  pull_request:
    branches:
      - master

jobs:
    create-rc-branch:

      runs-on: ubuntu-latest

      steps:
        - name: Set current datetime as env variable
          id: set-current-datetime
          env:
          TZ: 'Asia/Tokyo'
          run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

        - name: Checkout target branch
          uses: actions/checkout@v3
          with:
            ref: dev/7.0.x

        - name: Create RC release branch
          run: |
            git checkout -b rc/${{ steps.set-current-datetime.outputs.CURRENT_DATETIME }}
