name: Reusable build app workflow for production

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      skip-e2e-test:
        type: boolean
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:

  build-prod:
    runs-on: ubuntu-latest

    outputs:
      PROD_FILES: ${{ steps.archive-prod-files.outputs.file }}
      PROD_DEPS: ${{ steps.archive-prod-deps.outputs.file }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Git LFS
      run: |
        git lfs install

    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install turbo
      run: |
        pnpm add turbo --global

    - name: Install dependencies
      run: |
        pnpm install --frozen-lockfile

    - name: Cache/Restore dist
      uses: actions/cache@v4
      with:
        path: |
          **/.turbo
          **/dist
          **/node_modules/.cache/turbo
          ${{ github.workspace }}/apps/app/.next
        key: dist-app-prod-${{ runner.OS }}-node${{ inputs.node-version }}-${{ github.sha }}
        restore-keys: |
          dist-app-prod-${{ runner.OS }}-node${{ inputs.node-version }}-

    - name: Build
      working-directory: ./apps/app
      run: |
        turbo run build --env-mode=loose
      env:
        ANALYZE: 1

    - name: Assembling all dependencies
      run: |
        rm -rf out
        pnpm deploy out --prod --filter @growi/app
        rm -rf apps/app/node_modules && mv out/node_modules apps/app/node_modules

    - name: Archive production files
      id: archive-prod-files
      run: |
        tar -zcf production.tar.gz --exclude ./apps/app/.next/cache \
          package.json \
          apps/app/.next \
          apps/app/config \
          apps/app/dist \
          apps/app/public \
          apps/app/resource \
          apps/app/tmp \
          apps/app/.env.production* \
          apps/app/package.json
        echo "file=production.tar.gz" >> $GITHUB_OUTPUT

    - name: Archive production dependencies
      id: archive-prod-deps
      run: |
        tar -zcf production-deps.tar.gz \
          apps/app/node_modules
        echo "file=production-deps.tar.gz" >> $GITHUB_OUTPUT

    - name: Upload production files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Production Files (node${{ inputs.node-version }})
        path: ${{ steps.archive-prod-files.outputs.file }}

    - name: Upload production dependencies as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Production Dependencies (node${{ inputs.node-version }})
        path: ${{ steps.archive-prod-deps.outputs.file }}

    - name: Upload report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Bundle Analyzing Report (node${{ inputs.node-version }})
        path: |
          apps/app/.next/analyze

    - name: Slack Notification
      uses: weseek/ghaction-slack-notification@master
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: '*Node CI for growi - build-prod (${{ inputs.node-version }})*'
        channel: '#ci'
        isCompactMode: true
        url: ${{ secrets.SLACK_WEBHOOK_URL }}


  launch-prod:
    needs: [build-prod]
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
        - 27017/tcp
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
        ports:
        - 9200/tcp
        env:
          discovery.type: single-node

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Download production files artifact
      uses: actions/download-artifact@v4
      with:
        name: Production Files (node${{ inputs.node-version }})

    - name: Download production dependencies artifact
      uses: actions/download-artifact@v4
      with:
        name: Production Dependencies (node${{ inputs.node-version }})

    - name: Extract procution files and dependencies
      run: |
        tar -xf ${{ needs.build-prod.outputs.PROD_FILES }}
        tar -xf ${{ needs.build-prod.outputs.PROD_DEPS }}

    - name: pnpm run server:ci
      working-directory: ./apps/app
      run: |
        cp config/ci/.env.local.for-ci .env.production.local
        pnpm run server:ci
      env:
        MONGO_URI: mongodb://localhost:${{ job.services.mongodb.ports['27017'] }}/growi
        ELASTICSEARCH_URI: http://localhost:${{ job.services.elasticsearch.ports['9200'] }}/growi

    - name: Slack Notification
      uses: weseek/ghaction-slack-notification@master
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: '*Node CI for growi - build-prod (${{ inputs.node-version }})*'
        channel: '#ci'
        isCompactMode: true
        url: ${{ secrets.SLACK_WEBHOOK_URL }}


  run-playwright:
    needs: [build-prod]

    if: ${{ !inputs.skip-e2e-test && startsWith(github.head_ref, 'mergify/merge-queue/') }}

    runs-on: ubuntu-latest
    container:
      # Match the Playwright version
      # https://github.com/microsoft/playwright/issues/20010
      image: mcr.microsoft.com/playwright:v1.46.0-jammy

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        shard: [1/2, 2/2]

    services:
      mongodb:
        image: mongo:6.0
        ports:
        - 27017/tcp
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
        ports:
        - 9200/tcp
        env:
          discovery.type: single-node

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: |
        pnpm install --frozen-lockfile

    - name: Install Playwright browsers
      run: |
        pnpm playwright install --with-deps ${{ matrix.browser }}

    - name: Download production files artifact
      uses: actions/download-artifact@v4
      with:
        name: Production Files (node${{ inputs.node-version }})

    - name: Extract procution files artifact
      run: |
        tar -xf ${{ needs.build-prod.outputs.PROD_FILES }}

    - name: Copy dotenv file for ci
      working-directory: ./apps/app
      run: |
        cat config/ci/.env.local.for-ci >> .env.production.local

    - name: Playwright Run (--project=chromium/installer)
      if: ${{ matrix.browser == 'chromium' }}
      working-directory: ./apps/app
      run: |
        pnpm playwright test --project=chromium/installer
      env:
        HOME: /root # ref: https://github.com/microsoft/playwright/issues/6500
        MONGO_URI: mongodb://mongodb:27017/growi-playwright-installer
        ELASTICSEARCH_URI: http://localhost:${{ job.services.elasticsearch.ports['9200'] }}/growi

    - name: Copy dotenv file for automatic installation
      working-directory: ./apps/app
      run: |
        cat config/ci/.env.local.for-auto-install >> .env.production.local

    - name: Playwright Run
      working-directory: ./apps/app
      run: |
        pnpm playwright test --project=${{ matrix.browser }} --shard=${{ matrix.shard }}
      env:
        HOME: /root # ref: https://github.com/microsoft/playwright/issues/6500
        MONGO_URI: mongodb://mongodb:27017/growi-playwright
        ELASTICSEARCH_URI: http://localhost:${{ job.services.elasticsearch.ports['9200'] }}/growi

    - name: Copy dotenv file for automatic installation with allowing guest mode
      working-directory: ./apps/app
      run: |
        cat config/ci/.env.local.for-auto-install-with-allowing-guest >> .env.production.local

    - name: Playwright Run (--project=${browser}/guest-mode)
      working-directory: ./apps/app
      run: |
        pnpm playwright test --project=${{ matrix.browser }}/guest-mode --shard=${{ matrix.shard }}
      env:
        HOME: /root # ref: https://github.com/microsoft/playwright/issues/6500
        MONGO_URI: mongodb://mongodb:27017/growi-playwright-guest-mode
        ELASTICSEARCH_URI: http://localhost:${{ job.services.elasticsearch.ports['9200'] }}/growi

    - name: Slack Notification
      uses: weseek/ghaction-slack-notification@master
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: '*Node CI for growi - run-playwright*'
        channel: '#ci'
        isCompactMode: true
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
